-----------------------------------------
--       Справочники
-----------------------------------------

-- Финансовые позиции
CREATE TABLE IF NOT EXISTS fin_pos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pos VARCHAR(20) NOT NULL
);

INSERT INTO fin_pos (pos) VALUES 
('банкрот'),
('малоимущий'),
('средний заработок'),
('высокий заработок');

-- Гендеры
CREATE TABLE IF NOT EXISTS sex (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sex VARCHAR(3) NOT NULL
);

INSERT INTO sex (sex) VALUES 
('муж'),
('жен');

-- Типы пользователей
CREATE TABLE IF NOT EXISTS user_type (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(20) NOT NULL
);

INSERT INTO user_type (type) VALUES 
('клиент'),
('рабочий'),
('администратор');

-- Категории документов
CREATE TABLE IF NOT EXISTS category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(20) NOT NULL
);

INSERT INTO category (type) VALUES 
('кредитный договор'),
('выписка из счета'),
('счет');

-- Статусы операций
CREATE TABLE IF NOT EXISTS operation (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status VARCHAR(20) NOT NULL
);

INSERT INTO operation (status) VALUES 
('Загружен'),
('Ошибка загрузки');

-----------------------------------------
--       Основные таблицы
-----------------------------------------

-- Пользователи
CREATE TABLE IF NOT EXISTS app_user (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    middle_name VARCHAR,
    birthday DATE NOT NULL,
    fin_position_id INTEGER NOT NULL,
    address VARCHAR NOT NULL,
    inn BIGINT NOT NULL CHECK (inn BETWEEN 1000000000 AND 9999999999),
    sex_id INTEGER NOT NULL,
    user_type_id INTEGER NOT NULL
);

INSERT INTO app_user (
    first_name, last_name, middle_name, birthday, 
    fin_position_id, address, inn, sex_id, user_type_id
) VALUES
('Иван', 'Иванов', 'Иванович', '1990-01-01', 3, 'Москва, ул. Пушкина 1', 1234567890, 1, 1),
('Мария', 'Петрова', 'Сергеевна', '1985-05-15', 2, 'СПб, Невский пр. 5', 2345678901, 2, 2),
('Алексей', 'Смирнов', DEFAULT, '1978-12-31', 4, 'Казань, Кремлевская 10', 3456789012, 1, 3),
('Елена', 'Васильева', 'Олеговна', '1995-07-20', 1, 'Екатеринбург, Ленина 25', 4567890123, 2, 1),
('Дмитрий', 'Новиков', 'Петрович', '2000-03-10', 3, 'Новосибирск, Красный пр. 7', 5678901234, 1, 1);

-- Документы
CREATE TABLE IF NOT EXISTS document (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    link VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    user_id INTEGER NOT NULL,
    worker_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    actual_date DATE NOT NULL,
    actual_end_date DATE,
    plan_maturity_date DATE NOT NULL,
    fact_maturity_date DATE
);

INSERT INTO document (
    link, description, user_id, worker_id, category_id, 
    actual_date, plan_maturity_date
) VALUES
('doc1.pdf', 'Кредитный договор №1', 1, 2, 1, '2023-01-01', '2024-01-01'),
('doc2.pdf', 'Выписка за январь', 2, 3, 2, '2023-02-01', '2024-02-01'),
('doc3.pdf', 'Счет за коммуналку', 3, 2, 3, '2023-03-01', '2024-03-01'),
('doc4.pdf', 'Кредитный договор №2', 4, 3, 1, '2023-04-01', '2024-04-01'),
('doc5.pdf', 'Выписка за апрель', 5, 2, 2, '2023-05-01', '2024-05-01');

-- Статистика
CREATE TABLE IF NOT EXISTS stat (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    date DATE NOT NULL,
    document_id INTEGER NOT NULL,
    operation_status_id INTEGER NOT NULL
);

INSERT INTO stat (user_id, date, document_id, operation_status_id) VALUES
(1, '2023-01-01', 1, 1),
(2, '2023-02-01', 2, 1),
(3, '2023-03-01', 3, 1),
(4, '2023-04-01', 4, 1),
(5, '2023-05-01', 5, 1);

-- Контракты
CREATE TABLE IF NOT EXISTS contract (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    document_id INTEGER NOT NULL,
    operation_status_id INTEGER NOT NULL
);

INSERT INTO contract (user_id, document_id, operation_status_id) VALUES
(1, 1, 1),
(2, 2, 1),
(3, 3, 1),
(4, 4, 1),
(5, 5, 1);